language: java
jdk:
  - openjdk8
  - openjdk11
  - openjdk13
  - openjdk14

# No need for preliminary install step.
install: true
#
# Run all integration tests.
script: 
  - "mvn --show-version --errors --batch-mode clean verify"
#
cache:
    directories:
    - $HOME/.m2
branches:
    except:
        - gh-pages
notifications:
    email:
        - khmarbaise@apache.org
